### ISSUE TITLE
nullpointer when predicting with set model & threshold

### ISSUE THREAD

**Issue by joergwicker** [enviPath/enviPath#78] opened 2016-09-01 15:44 UTC
Trying to predict a model with a setting returns a nullpointer.

**Comment by steven-lang** [comment] 2016-09-04 14:01
This may be due to an old model which was not stored correctly (since the model and it's evaluation has changed a lot in the last few commits). I could not reproduce this bug yet

**Comment by steven-lang** [comment] 2016-10-20 19:37
Closing since the issue is still not reproducible.

**Closed by steven-lang** 2016-10-20 19:37 UTC
Labels: high priority
